#!/bin/ksh

INFORMIXDIR=/opt/ids1170fc5
INFORMIXSERVER=ids_demo
ONCONFIG=onconfig.ids_demo
INFORMIXSQLHOSTS=$INFORMIXDIR/etc/sqlhosts
TERMCAP=$INFORMIXDIR/etc/termcap

PATH=$INFORMIXDIR/bin:$PATH

#DB_LOCALE=hr_HR.852
#CLIENT_LOCALE=hr_HR.852
#DBDATE=DMY4/

DBEDIT=vim

export INFORMIXDIR INFORMIXSERVER ONCONFIG INFORMIXSQLHOSTS PATH TERMCAP

#export DB_LOCALE CLIENT_LOCALE DBDATE

export DBEDIT
